// <auto-generated />
using System;
using Employee.Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Employee.Dataa.Migrations
{
    [DbContext(typeof(EmployeeDbContext))]
    [Migration("20210216110205_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Employee.Data.Models.CompanyModels", b =>
                {
                    b.Property<int>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CompanyCity")
                        .HasColumnType("text");

                    b.Property<string>("CompanyName")
                        .HasColumnType("text");

                    b.HasKey("CompanyId");

                    b.ToTable("CompanyModels");
                });

            modelBuilder.Entity("Employee.Data.Models.PersonModels", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int?>("CompanyModelsCompanyId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<string>("Surname")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CompanyModelsCompanyId");

                    b.ToTable("personModels");
                });

            modelBuilder.Entity("Employee.Data.Models.PersonModels", b =>
                {
                    b.HasOne("Employee.Data.Models.CompanyModels", "CompanyModels")
                        .WithMany("PersonModels")
                        .HasForeignKey("CompanyModelsCompanyId");
                });
#pragma warning restore 612, 618
        }
    }
}
